version: "3.8"

services:
  web:
    build: .
    container_name: tulahack-back-26
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hackaton

volumes:
  postgres:
